apiVersion: servicecatalog.k8s.io/v1alpha1
kind: ServiceInstanceCredential
metadata:
  name: {{ template "fullname" . }}-cosmosdb-credential
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  instanceRef:
    name: {{ template "fullname" . }}-cosmosdb-instance
  secretName: {{ template "fullname" . }}-cosmosdb-secret
