apiVersion: servicecatalog.k8s.io/v1alpha1
kind: ServiceInstance
metadata:
  name: {{ template "fullname" . }}-cosmosdb-instance
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  serviceClassName: azure-document-db
  planName: DocumentDB
  parameters:
    location: "{{ .Values.location }}"
    resourceGroup: "{{ .Values.resourceGroup }}"
    sslEnforcement: disabled
